title: SIDEREVS NVNCIVS
email: mrcsvoliveira@gmail.com
description: Site sobre astronomia, astrofísica, ensino de física.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://github.com/sidereus-nuncius/sidereus-nuncius.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

twitter: marcvenicios 
github: marcosvoliveira
quora: Marcos-V-Oliveira

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate: 4

navigation:
  - title: Inicio
    url: /index.html
  - title: Artigos
    url: /post
  - title: Sobre
    url: /Sobre
  - title: Contatos
    url: /contatos



